mail-host: localhost
frontend-host: 'http://localhost:4200'

spring:
  application:
    name: security
  security:
    auth:
      header: Authorization
      bearer: 'Bearer '
      secret-key: '19b5dc3e3439f76664c98f81633850ca56fee65dd9be03f8b5c09cc229f64266'
      expiration: 86400000
      characters: '0123456789'
      act-token-length: 6
      act-token-exp-time: 15
  datasource:
    url: jdbc:postgresql://localhost:5432/book_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${mail-host}
    port: 1025
    username: great
    password: great
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connection-timeout: 5000
        timeout: 3000
        write-timeout: 5000
  mailing:
    frontend:
      activation-url: '${frontend-host}/activate-account'
    subject:
      activation: 'Account activation'
server:
  port: 8088